### ISSUE TITLE
Can I run build using your plugin?

### ISSUE THREAD

**Issue by dev2see** [JetBrains/teamcity-rest-client#24]
Can I run build with parameters using your plugin?

**Comment by ortin** [comment]
Anyone? Coz documentation is not existent.

**Comment by shalupov** [comment]
Sorry, not yet. Here we implement only interfaces we use ourselves (but we review pull requests too).
For a running a custom build one still needs to use REST API:
https://confluence.jetbrains.com/display/TCD10/REST+API#RESTAPI-TriggeringaBuild
