### ISSUE TITLE
wish list: add to maven central

### ISSUE THREAD

**Issue by kenkyee** [JetBrains/teamcity-rest-client#4]
I know...it's only 3 files, but would be good to put it up so people can pull down updates automatically :-)

**Comment by shalupov** [comment]
It's on bintray: https://bintray.com/jetbrains/teamcity-rest-client/teamcity-rest-client/view

**Comment by kenkyee** [comment]
Thanks...wasn't on jcenter, so I had to use the url syntax to find it in my build.gradle:
ext.teamcity_client_version = '0.1.45'
repositories {
    jcenter()
    maven { url "http://dl.bintray.com/jetbrains/teamcity-rest-client" }
}
