### ISSUE TITLE
[Question] How to specify endDate in BuildLocator?

### ISSUE THREAD

**Issue by blindpirate** [JetBrains/teamcity-rest-client#51]
I can only find `sinceDate` in `BuildLocator`, how to get builds in a specific period? Previously we use REST API `startDate:(date: xxx, condition: after), startDate(date:xxx, condition:before)`.

Thanks in advance.

**Comment by shalupov** [comment]
It seems it's impossible now, but we accept PRs :) Probably it's worth adding `untilDate`

**Comment by blindpirate** [comment]
PR created in https://github.com/JetBrains/teamcity-rest-client/pull/54
