### ISSUE TITLE
Migrate publication from JCenter and Bintray

### ISSUE THREAD

**Issue by goodwinnk** [JetBrains/teamcity-rest-client#97]
Because artefacts are going to be lost soon: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by VladRassokhin** [comment]
Done in https://github.com/JetBrains/teamcity-rest-client/commit/27410f13ef84fb722ec9c94500c4e0febe17b9ab
